name: Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push-amd64:
    name: Docker image amd64
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/base
          file: Docker/base/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
          tags: mcgillrobotics/drone_capstone:base-amd64
          
  build-and-push-arm64:
    name: Docker image arm64
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/base
          file: Docker/base/Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
          tags: mcgillrobotics/drone_capstone:base-arm64

  build-and-push-base:
    name: multi-arch Docker image
    runs-on: ubuntu-22.04
    needs:
      - build-and-push-amd64
      - build-and-push-arm64
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create multi-arch base image manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: mcgillrobotics/drone_capstone:base
          sources: |
            mcgillrobotics/drone_capstone:base-amd64
            mcgillrobotics/drone_capstone:base-arm64

  build-and-push-foxy:
    name: Docker image foxy
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/foxy
          file: Docker/foxy/Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
          tags: mcgillrobotics/drone_capstone:foxy
  
  build-and-push-humble:
    name: Docker image humble
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/humble
          file: Docker/humble/Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
          tags: mcgillrobotics/drone_capstone:humble
  
  build-and-push-jetson:
    name: Docker image jetson
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only if pushing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and optionally push image
        uses: docker/build-push-action@v5
        with:
          context: Docker/jetson
          file: Docker/jetson/Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
          tags: mcgillrobotics/drone_capstone:jetson
